version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
      tag: '12.14.1-browsers'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn lint
      - run: yarn cy:ci
